language: node_js
dist: trusty
sudo: required

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - OCI_LIB_DIR=/u01/app/oracle/product/11.2.0/xe/lib
    - LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib
    - ORACLE_SID=XE


services:
  - mysql
  - postgresql

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - export PATH=$ORACLE_HOME/bin/:$PATH
  - sqlplus -V
  - psql --version
  - mysql --version
  - yarn add oracledb
  - mysql -e "CREATE USER 'travis'@'%';GRANT ALL PRIVILEGES TO 'travis'@'%' WITH GRANT OPTION";

node_js:
  - "4"
  - "6"

after_success: npm run report-coverage
